# Generated by Django 5.0.6 on 2024-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_resetpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
